### ISSUE TITLE
Rename the repository as Tensorflow_Toolkit and archive the current Tensorflow_Toolkit repository

### ISSUE THREAD

**Issue by epignatelli** [BHoM/TensorFlow_Toolkit#23]
#### Broken rules:

The difference in the functionalities is currently unclear.

#### Suggestions to restore compliance:

As per title, we should archive che current Tensorflow_Toolkit and replace it with the current repo

**Comment by FraserGreenroyd** [comment]
This is now complete with the previous TensorFlow_Toolkit now being archived and called TensorFlow_Toolkit_Old.
